// web-stencil/src/components/main-footer/main-footer.tsx
import { Component, Host, h, Prop } from '@stencil/core';

@Component({
  tag: 'main-footer',
  styleUrl: 'main-footer.scss',
  shadow: true,
})
export class MainFooter {
  @Prop() menuOpened!: boolean;
  @Prop() menuWidth!: number;
  @Prop() isMobile?: boolean = false;

  render() {
    const hostStyle = this.isMobile
      ? { width: '100vw', display: 'none' } // Hide footer on mobile to save space
      : { width: `calc(100vw - ${this.menuOpened ? this.menuWidth : 0}px)` };

    return (
      <Host class={{ 'mobile': this.isMobile || false, 'desktop': !this.isMobile }} style={hostStyle}>
        <footer
                class='footer bg-gray-400 backdrop-filter backdrop-blur-lg bg-opacity-10  firefox:bg-opacity-90'>
          <div>
            Built with 💖 and :
            <p style={{ fontSize: '.8rem' }}>
              <span>StencilJS</span> • <span>TypeScript</span> • <span>ThreeJS</span> • <span>enable3d</span> <br />
              <span>AmmoJS</span> • <span>Tailwind</span>
            </p>
          </div>
        </footer>
      </Host>
    );
  }

}

// web-astro/src/components/shell/MainFooter.tsx
// PORT TARGET: web-stencil/src/components/main-footer/main-footer.tsx
//
// Parity goals:
// - Hidden on mobile (display: none)
// - Width matches main content (calc(100vw - {menuWidth}px))
// - Backdrop blur + transparent background
// - "Built with 💖 and: StencilJS • TypeScript • ThreeJS • enable3d • AmmoJS • Tailwind"
//   (will need updating to reflect the new stack post-migration)

import { Show } from 'solid-js';
import { menuOpened, menuWidth, isMobile } from '../../stores/shell';

export default function MainFooter() {
  return (
    <Show when={!isMobile()}>
      <footer
        class="fixed bottom-0 left-0 z-20 px-4 py-2 bg-gray-400/10 backdrop-blur-lg text-xs text-gray-300"
        style={`width:calc(100vw - ${menuOpened() ? menuWidth() : 0}px);`}
      >
        Built with 💖 and:{' '}
        <span class="text-gray-400">
          StencilJS • TypeScript • ThreeJS • enable3d • AmmoJS • Tailwind
        </span>
      </footer>
    </Show>
  );
}
